version: '3.8'

services:
  bot-platform:
    build: .
    container_name: list_company_bot_saas
    restart: always
    environment:
      - MOTHER_TOKEN=${MOTHER_TOKEN}
      - MASTER_ADMIN_ID=${MASTER_ADMIN_ID}
      - DB_FILE=/data/bot_platform.db
      - DOMAIN_URL=${DOMAIN_URL}
    volumes:
      - ./data:/data
    ports:
      - "8081:8000"
