version: '3.8'

services:
  bot-platform:
    build: .
    container_name: list_company_bot_saas
    restart: always
    environment:
      - MOTHER_TOKEN=${MOTHER_TOKEN}
      - MASTER_ADMIN_IDS=${MASTER_ADMIN_IDS}
      - DB_FILE=/data/bot_platform.db
      - DOMAIN_URL=${DOMAIN_URL}
      - MEDIA_DIR=/data/media
    volumes:
      - ./data:/data
      - ./data/backups:/data/backups
      - ./media:/data/media
    ports:
      - "8085:8000"
